# Generated by Django 2.1.15 on 2022-11-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('tweet', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=20)),
                ('hashtags', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tweets',
            unique_together={('category', 'tweet', 'user', 'hashtags', 'mood')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('userid', 'category')},
        ),
    ]
